
#
# As a Qt6 app similar to OBS, should be loosly based on:
# https://github.com/obsproject/obs-studio/blob/master/.github/workflows/main.yml
#

name: CI

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch

jobs:
  #
  # As a Qt6 app similar to OBS, should be loosly based on:
  # https://github.com/obsproject/obs-studio/blob/master/.github/workflows/main.yml#L282 +/- a few lines
  #
  windows_build:
    name: Windows
    runs-on: [windows-2022]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.1
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: qtmultimedia
          tools: tools_ifw
          setup-python: false

      - name: Install Qt JOM
        working-directory: ${{ env.QT_ROOT_DIR }}
        shell: cmd
        run: |
          mkdir ..\..\Tools\QtCreator\bin\
          pushd ..\..\Tools\QtCreator\bin\
          curl -s -L -o jom.zip http://download.qt.io/official_releases/jom/jom.zip
          7z x jom.zip -ojom
          del jom.zip
          popd

      - name: Build & Package
        id: buildAndPackage
        shell: pwsh
        run: |
          CI\windows-build.ps1 "CONFIG+=package"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtNdiMonitorCaptureInstaller
          path: ${{ github.workspace }}/app/installer/QtNdiMonitorCaptureInstaller.exe

      - name: Upload Release
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ github.workspace }}/app/installer/QtNdiMonitorCaptureInstaller.exe
          overwrite: true
